### ISSUE TITLE
Not working in Mac Safari

### ISSUE THREAD

**Issue by ngtrducthuan** [yumexupanic/wsfmp4.js#4]
Hello there,

I'm working on a private project and encountered a similar issue. When feeding the SourceBuffer, I get the error InvalidStateError: The object is in an invalid state.

Could you please take a look and help fix it?

**Comment by yumexupanic** [comment]
Could you please check if the same code works in Chrome or any other browsers

**Comment by ngtrducthuan** [comment]
(this.sourceBuffer.appendBuffer(s), this.options.debug && console.log(`load buffer: size => ${s.byteLength}`))

We are getting below error in Mac Safari...

    [Error] InvalidStateError: The object is in an invalid state.
	appendBuffer (index-Bbp2-xcD.js:17:149775)
	_cache (index-Bbp2-xcD.js:17:149775)
	(anonymous function) (index-Bbp2-xcD.js:17:146868)

**Comment by ngtrducthuan** [comment]
We can see it works well on Chrome, but Safari is dead after append some data to Media Source...

**Comment by ngtrducthuan** [comment]
As we are still facing issue in Safari, keep it open...

**Comment by ngtrducthuan** [comment]
Mark it as Open,... please
